development:
  # Configure available database clients. (required)
  clients:
    default:
      uri: 'mongodb://root:root@ds051523.mongolab.com:51523/no_sql_crud'
      options: 
        consistency: :strong
        max_retries: 30
        retry_interval: 1
        timeout: 15
  options:
    # Includes the root model name in json serialization. (default: false)
    # include_root_in_json: false

    # Include the _type field in serialization. (default: false)
    # include_type_for_serialization: false

    # Preload all models in development, needed when models use
    # inheritance. (default: false)
    # preload_models: false

    # Raise an error when performing a #find and the document is not found.
    # (default: true)
    # raise_not_found_error: true

    # Raise an error when defining a scope with the same name as an
    # existing method. (default: false)
    # scope_overwrite_exception: false

    # Use Active Support's time zone in conversions. (default: true)
    # use_activesupport_time_zone: true

    # Ensure all times are UTC in the app side. (default: false)
    # use_utc: false
test:
  clients:
    default:
      database: no_sql_crud_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: primary
        max_pool_size: 1
production:
  clients:
    default:
      uri: 'mongodb://root:root@ds051523.mongolab.com:51523/no_sql_crud'
      options:
        skip_version_check: true
        safe: true